services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    ports:
      - "8000:8000"
    restart: always

  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "3001:3000"
    env_file:
      - ./config.env
    environment:
      MONGODB_URI: mongodb://mongo:27017/gawdee
    depends_on:
      - mongo
      - centrifugo
    restart: always

volumes:
  mongo_data:
